apiVersion: v1
kind: ConfigMap
metadata:
  name: zai-cts-config
data:
  ENVIRONMENT: "production"
  SERVICE_NAME: "carbon-registry-service"
  CARBON_REGISTRY_URL: "http://carbon-registry-service:8101"
